const vocabulary = [
    // ... collez la liste COMPLÈTE des mots ici ...
  {"anglais": "a/an", "francais": "un/une"},
  {"anglais": "a few", "francais": "quelques"},
  {"anglais": "able", "francais": "capable"},
  {"anglais": "about", "francais": "environ, à propos de"},
  {"anglais": "above", "francais": "au-dessus"},
  {"anglais": "accident", "francais": "accident"},
  {"anglais": "across", "francais": "à travers, de l'autre côté"},
  {"anglais": "act", "francais": "acte, jouer"},
  {"anglais": "action", "francais": "action"},
  {"anglais": "activity", "francais": "activité"},
  {"anglais": "actor", "francais": "acteur"},
  {"anglais": "actually", "francais": "en fait, réellement"},
  {"anglais": "ad", "francais": "publicité (abrégé)"},
  {"anglais": "add", "francais": "ajouter"},
  {"anglais": "address", "francais": "adresse"},
  {"anglais": "adult", "francais": "adulte"},
  {"anglais": "advanced", "francais": "avancé"},
  {"anglais": "adventure", "francais": "aventure"},
  {"anglais": "advert", "francais": "publicité (abrégé)"},
  {"anglais": "advertisement", "francais": "publicité"},
  {"anglais": "advice", "francais": "conseil(s)"},
  {"anglais": "aeroplane", "francais": "avion"},
  {"anglais": "afraid", "francais": "effrayé, avoir peur"},
  {"anglais": "after", "francais": "après"},
  {"anglais": "afternoon", "francais": "après-midi"},
  {"anglais": "afterwards", "francais": "ensuite"},
  {"anglais": "again", "francais": "encore, à nouveau"},
  {"anglais": "against", "francais": "contre"},
  {"anglais": "age", "francais": "âge"},
  {"anglais": "aged", "francais": "âgé"},
  {"anglais": "ago", "francais": "il y a"},
  {"anglais": "agree", "francais": "être d'accord"},
  {"anglais": "air", "francais": "air"},
  {"anglais": "airport", "francais": "aéroport"},
  {"anglais": "alarm clock", "francais": "réveil"},
  {"anglais": "album", "francais": "album"},
  {"anglais": "all", "francais": "tout, tous"},
  {"anglais": "all kinds of", "francais": "toutes sortes de"},
  {"anglais": "allow", "francais": "permettre"},
  {"anglais": "all right/alright", "francais": "d'accord, bien"},
  {"anglais": "all sorts of", "francais": "toutes sortes de"},
  {"anglais": "all the time", "francais": "tout le temps"},
  {"anglais": "almost", "francais": "presque"},
  {"anglais": "alone", "francais": "seul"},
  {"anglais": "along", "francais": "le long de"},
  {"anglais": "already", "francais": "déjà"},
  {"anglais": "alright", "francais": "d'accord, bien"},
  {"anglais": "also", "francais": "aussi"},
  {"anglais": "always", "francais": "toujours"},
  {"anglais": "a.m.", "francais": "du matin (ante meridiem)"},
  {"anglais": "amazed", "francais": "étonné, stupéfait"},
  {"anglais": "amazing", "francais": "incroyable, étonnant"},
  {"anglais": "ambulance", "francais": "ambulance"},
  {"anglais": "among", "francais": "parmi"},
  {"anglais": "an", "francais": "un/une"},
  {"anglais": "and", "francais": "et"},
  {"anglais": "angry", "francais": "en colère"},
  {"anglais": "animal", "francais": "animal"},
  {"anglais": "another", "francais": "un autre"},
  {"anglais": "answer", "francais": "réponse, répondre"},
  {"anglais": "any", "francais": "n'importe quel, aucun (négation), du/de la/des (interrogation)"},
  {"anglais": "anybody", "francais": "quelqu'un, personne (négation)"},
  {"anglais": "anymore", "francais": "ne...plus"},
  {"anglais": "anyone", "francais": "quelqu'un, personne (négation)"},
  {"anglais": "anything", "francais": "quelque chose, rien (négation)"},
  {"anglais": "anyway", "francais": "de toute façon"},
  {"anglais": "anywhere", "francais": "n'importe où, nulle part (négation)"},
  {"anglais": "apartment", "francais": "appartement"},
  {"anglais": "apartment building", "francais": "immeuble d'appartements"},
  {"anglais": "app", "francais": "application"},
  {"anglais": "apple", "francais": "pomme"},
  {"anglais": "appointment", "francais": "rendez-vous"},
  {"anglais": "area", "francais": "zone, région"},
  {"anglais": "arm", "francais": "bras"},
  {"anglais": "armchair", "francais": "fauteuil"},
  {"anglais": "around", "francais": "autour"},
  {"anglais": "arrive", "francais": "arriver"},
  {"anglais": "art", "francais": "art"},
  {"anglais": "article", "francais": "article"},
  {"anglais": "artist", "francais": "artiste"},
  {"anglais": "as", "francais": "comme, en tant que"},
  {"anglais": "ask", "francais": "demander"},
  {"anglais": "assistant", "francais": "assistant"},
  {"anglais": "as well", "francais": "aussi"},
  {"anglais": "as well as", "francais": "ainsi que"},
  {"anglais": "at", "francais": "à, chez"},
  {"anglais": "at / @", "francais": "à / arobase"},
  {"anglais": "at all", "francais": "du tout"},
  {"anglais": "attractive", "francais": "attrayant, séduisant"},
  {"anglais": "aunt", "francais": "tante"},
  {"anglais": "autumn", "francais": "automne"},
  {"anglais": "available", "francais": "disponible"},
  {"anglais": "away", "francais": "loin, absent"},
  {"anglais": "awesome", "francais": "génial, super"},
  {"anglais": "awful", "francais": "affreux, horrible"},
  {"anglais": "baby", "francais": "bébé"},
  {"anglais": "back", "francais": "dos, arrière, retour"},
  {"anglais": "backpack", "francais": "sac à dos"},
  {"anglais": "bad", "francais": "mauvais"},
  {"anglais": "badly", "francais": "mal"},
  {"anglais": "badminton", "francais": "badminton"},
  {"anglais": "bag", "francais": "sac"},
  {"anglais": "bake", "francais": "cuire au four"},
  {"anglais": "ball", "francais": "balle, ballon"},
  {"anglais": "balloon", "francais": "ballon (de baudruche)"},
  {"anglais": "banana", "francais": "banane"},
  {"anglais": "band", "francais": "groupe (musique)"},
  {"anglais": "bank", "francais": "banque"},
  {"anglais": "barbecue", "francais": "barbecue"},
  {"anglais": "baseball", "francais": "baseball"},
  {"anglais": "basketball", "francais": "basketball"},
  {"anglais": "bat", "francais": "batte (sport), chauve-souris"},
  {"anglais": "bath", "francais": "bain"},
  {"anglais": "bathing suit", "francais": "maillot de bain"},
  {"anglais": "bathroom", "francais": "salle de bain"},
  {"anglais": "bathtub", "francais": "baignoire"},
  {"anglais": "battery", "francais": "batterie, pile"},
  {"anglais": "be", "francais": "être"},
  {"anglais": "beach", "francais": "plage"},
  {"anglais": "bean", "francais": "haricot"},
  {"anglais": "bear", "francais": "ours"},
  {"anglais": "beard", "francais": "barbe"},
  {"anglais": "beautiful", "francais": "beau, belle"},
  {"anglais": "because", "francais": "parce que"},
  {"anglais": "because of", "francais": "à cause de"},
  {"anglais": "become", "francais": "devenir"},
  {"anglais": "bed", "francais": "lit"},
  {"anglais": "bedroom", "francais": "chambre"},
  {"anglais": "bee", "francais": "abeille"},
  {"anglais": "before", "francais": "avant"},
  {"anglais": "begin", "francais": "commencer"},
  {"anglais": "beginner", "francais": "débutant"},
  {"anglais": "beginning", "francais": "début"},
  {"anglais": "behind", "francais": "derrière"},
  {"anglais": "believe", "francais": "croire"},
  {"anglais": "belong", "francais": "appartenir"},
  {"anglais": "below", "francais": "en dessous"},
  {"anglais": "belt", "francais": "ceinture"},
  {"anglais": "beside", "francais": "à côté de"},
  {"anglais": "best", "francais": "le/la meilleur(e)"},
  {"anglais": "better", "francais": "meilleur, mieux"},
  {"anglais": "between", "francais": "entre"},
  {"anglais": "bicycle", "francais": "vélo"},
  {"anglais": "big", "francais": "grand"},
  {"anglais": "bike", "francais": "vélo"},
  {"anglais": "bill", "francais": "addition, facture"},
  {"anglais": "bin", "francais": "poubelle"},
  {"anglais": "biology", "francais": "biologie"},
  {"anglais": "bird", "francais": "oiseau"},
  {"anglais": "birth", "francais": "naissance"},
  {"anglais": "birthday", "francais": "anniversaire"},
  {"anglais": "biscuit", "francais": "biscuit (sec)"},
  {"anglais": "bit", "francais": "morceau, un peu"},
  {"anglais": "black", "francais": "noir"},
  {"anglais": "blackboard", "francais": "tableau noir"},
  {"anglais": "blanket", "francais": "couverture"},
  {"anglais": "block", "francais": "pâté de maisons, bloc"},
  {"anglais": "blog", "francais": "blog"},
  {"anglais": "blond(e)", "francais": "blond(e)"},
  {"anglais": "blood", "francais": "sang"},
  {"anglais": "blouse", "francais": "chemisier"},
  {"anglais": "blue", "francais": "bleu"},
  {"anglais": "board", "francais": "tableau, planche"},
  {"anglais": "board game", "francais": "jeu de société"},
  {"anglais": "boat", "francais": "bateau"},
  {"anglais": "body", "francais": "corps"},
  {"anglais": "boil", "francais": "bouillir"},
  {"anglais": "boiled", "francais": "bouilli"},
  {"anglais": "book", "francais": "livre, réserver"},
  {"anglais": "bookcase", "francais": "bibliothèque (meuble)"},
  {"anglais": "bookshelf", "francais": "étagère (à livres)"},
  {"anglais": "bookshop", "francais": "librairie"},
  {"anglais": "bookstore", "francais": "librairie"},
  {"anglais": "boot", "francais": "botte"},
  {"anglais": "bored", "francais": "qui s'ennuie"},
  {"anglais": "boring", "francais": "ennuyeux"},
  {"anglais": "born", "francais": "né"},
  {"anglais": "borrow", "francais": "emprunter"},
  {"anglais": "boss", "francais": "patron"},
  {"anglais": "both", "francais": "les deux"},
  {"anglais": "bother", "francais": "déranger"},
  {"anglais": "bottle", "francais": "bouteille"},
  {"anglais": "bottom", "francais": "bas, fond"},
  {"anglais": "bowl", "francais": "bol"},
  {"anglais": "box", "francais": "boîte"},
  {"anglais": "boy", "francais": "garçon"},
  {"anglais": "boyfriend", "francais": "petit ami"},
  {"anglais": "bracelet", "francais": "bracelet"},
  {"anglais": "brain", "francais": "cerveau"},
  {"anglais": "brave", "francais": "courageux"},
  {"anglais": "bread", "francais": "pain"},
  {"anglais": "break", "francais": "pause, casser"},
  {"anglais": "break down", "francais": "tomber en panne"},
  {"anglais": "breakfast", "francais": "petit déjeuner"},
  {"anglais": "bridge", "francais": "pont"},
  {"anglais": "bright", "francais": "vif, lumineux"},
  {"anglais": "brilliant", "francais": "brillant, génial"},
  {"anglais": "bring", "francais": "apporter"},
  {"anglais": "bring back", "francais": "rapporter"},
  {"anglais": "broken", "francais": "cassé"},
  {"anglais": "brother", "francais": "frère"},
  {"anglais": "brown", "francais": "marron"},
  {"anglais": "brush", "francais": "brosse, brosser"},
  {"anglais": "build", "francais": "construire"},
  {"anglais": "building", "francais": "bâtiment"},
  {"anglais": "burger", "francais": "hamburger"},
  {"anglais": "bus", "francais": "bus"},
  {"anglais": "business", "francais": "affaires, commerce"},
  {"anglais": "businessman", "francais": "homme d'affaires"},
  {"anglais": "businesswoman", "francais": "femme d'affaires"},
  {"anglais": "business person", "francais": "personne d'affaires"},
  {"anglais": "bus station", "francais": "gare routière"},
  {"anglais": "bus stop", "francais": "arrêt de bus"},
  {"anglais": "busy", "francais": "occupé"},
  {"anglais": "but", "francais": "mais"},
  {"anglais": "butter", "francais": "beurre"},
  {"anglais": "butterfly", "francais": "papillon"},
  {"anglais": "buy", "francais": "acheter"},
  {"anglais": "by", "francais": "par, près de"},
  {"anglais": "bye", "francais": "au revoir, salut"},
  {"anglais": "cabinet", "francais": "placard, armoire"},
  {"anglais": "cafe/café", "francais": "café (lieu)"},
  {"anglais": "cafeteria", "francais": "cafétéria"},
  {"anglais": "cake", "francais": "gâteau"},
  {"anglais": "calendar", "francais": "calendrier"},
  {"anglais": "call", "francais": "appel, appeler"},
  {"anglais": "camel", "francais": "chameau"},
  {"anglais": "camera", "francais": "appareil photo"},
  {"anglais": "camp", "francais": "camper"},
  {"anglais": "camping", "francais": "camping"},
  {"anglais": "campsite", "francais": "terrain de camping"},
  {"anglais": "can", "francais": "boîte (conserve), pouvoir (capacité, permission, possibilité), savoir (faire qqch)"},
  {"anglais": "candy", "francais": "bonbon"},
  {"anglais": "cannot", "francais": "ne pas pouvoir"},
  {"anglais": "cap", "francais": "casquette"},
  {"anglais": "capital", "francais": "capitale, majuscule"},
  {"anglais": "car", "francais": "voiture"},
  {"anglais": "card", "francais": "carte"},
  {"anglais": "career", "francais": "carrière"},
  {"anglais": "careful", "francais": "prudent, attentionné"},
  {"anglais": "carefully", "francais": "prudemment, attentivement"},
  {"anglais": "car park", "francais": "parking"},
  {"anglais": "carpet", "francais": "moquette, tapis"},
  {"anglais": "carrot", "francais": "carotte"},
  {"anglais": "carry", "francais": "porter"},
  {"anglais": "cartoon", "francais": "dessin animé"},
  {"anglais": "case", "francais": "étui, cas, affaire"},
  {"anglais": "cash", "francais": "espèces, argent liquide"},
  {"anglais": "castle", "francais": "château"},
  {"anglais": "cat", "francais": "chat"},
  {"anglais": "catch", "francais": "attraper"},
  {"anglais": "CD", "francais": "CD"},
  {"anglais": "CD player", "francais": "lecteur CD"},
  {"anglais": "ceiling", "francais": "plafond"},
  {"anglais": "cell phone", "francais": "téléphone portable"},
  {"anglais": "celebrate", "francais": "célébrer"},
  {"anglais": "celebrity", "francais": "célébrité"},
  {"anglais": "cent", "francais": "centime"},
  {"anglais": "centre/center", "francais": "centre"},
  {"anglais": "centimetre/centimeter (cm)", "francais": "centimètre (cm)"},
  {"anglais": "century", "francais": "siècle"},
  {"anglais": "cereal", "francais": "céréales"},
  {"anglais": "certainly", "francais": "certainement"},
  {"anglais": "chain", "francais": "chaîne"},
  {"anglais": "chair", "francais": "chaise"},
  {"anglais": "change", "francais": "changer, monnaie, changement"},
  {"anglais": "channel", "francais": "chaîne (télévision)"},
  {"anglais": "character", "francais": "personnage"},
  {"anglais": "chat", "francais": "discussion, bavarder"},
  {"anglais": "chatroom", "francais": "salon de discussion"},
  {"anglais": "cheap", "francais": "bon marché"},
  {"anglais": "check", "francais": "vérifier"},
  {"anglais": "cheese", "francais": "fromage"},
  {"anglais": "chef", "francais": "chef cuisinier"},
  {"anglais": "chemist", "francais": "pharmacien, pharmacie"},
  {"anglais": "chemistry", "francais": "chimie"},
  {"anglais": "cheque", "francais": "chèque"},
  {"anglais": "chess", "francais": "échecs"},
  {"anglais": "chicken", "francais": "poulet"},
  {"anglais": "child", "francais": "enfant"},
  {"anglais": "chilli", "francais": "piment"},
  {"anglais": "chips", "francais": "frites"},
  {"anglais": "chocolate", "francais": "chocolat"},
  {"anglais": "choose", "francais": "choisir"},
  {"anglais": "cinema", "francais": "cinéma"},
  {"anglais": "circle", "francais": "cercle"},
  {"anglais": "circus", "francais": "cirque"},
  {"anglais": "city", "francais": "ville"},
  {"anglais": "class", "francais": "classe, cours"},
  {"anglais": "classical", "francais": "classique"},
  {"anglais": "classmate", "francais": "camarade de classe"},
  {"anglais": "classroom", "francais": "salle de classe"},
  {"anglais": "clean", "francais": "propre, nettoyer"},
  {"anglais": "cleaner", "francais": "nettoyeur, femme de ménage"},
  {"anglais": "clear", "francais": "clair"},
  {"anglais": "clearly", "francais": "clairement"},
  {"anglais": "clever", "francais": "intelligent"},
  {"anglais": "click", "francais": "clic, cliquer"},
  {"anglais": "climb", "francais": "grimper, escalader"},
  {"anglais": "climbing", "francais": "escalade"},
  {"anglais": "clock", "francais": "horloge"},
  {"anglais": "close", "francais": "proche, fermer"},
  {"anglais": "closed", "francais": "fermé"},
  {"anglais": "closet", "francais": "placard"},
  {"anglais": "clothes", "francais": "vêtements"},
  {"anglais": "cloud", "francais": "nuage"},
  {"anglais": "cloudy", "francais": "nuageux"},
  {"anglais": "clown", "francais": "clown"},
  {"anglais": "club", "francais": "club"},
  {"anglais": "coach", "francais": "autocar, entraîneur"},
  {"anglais": "coast", "francais": "côte"},
  {"anglais": "coat", "francais": "manteau"},
  {"anglais": "coffee", "francais": "café (boisson)"},
  {"anglais": "cola", "francais": "coca"},
  {"anglais": "cold", "francais": "froid"},
  {"anglais": "colleague", "francais": "collègue"},
  {"anglais": "collect", "francais": "collectionner, ramasser"},
  {"anglais": "college", "francais": "collège, université (selon pays)"},
  {"anglais": "colour", "francais": "couleur, colorier"},
  {"anglais": "comb", "francais": "peigne, peigner"},
  {"anglais": "come", "francais": "venir"},
  {"anglais": "come back", "francais": "revenir"},
  {"anglais": "comedy", "francais": "comédie"},
  {"anglais": "comfortable", "francais": "confortable"},
  {"anglais": "comic", "francais": "bande dessinée"},
  {"anglais": "company", "francais": "entreprise"},
  {"anglais": "competition", "francais": "compétition"},
  {"anglais": "complete", "francais": "compléter"},
  {"anglais": "computer", "francais": "ordinateur"},
  {"anglais": "concert", "francais": "concert"},
  {"anglais": "congratulations!", "francais": "félicitations !"},
  {"anglais": "contact", "francais": "contact, contacter"},
  {"anglais": "continue", "francais": "continuer"},
  {"anglais": "conversation", "francais": "conversation"},
  {"anglais": "cook", "francais": "cuisinier, cuisiner"},
  {"anglais": "cooker", "francais": "cuisinière"},
  {"anglais": "cookie", "francais": "biscuit (rond et sucré)"},
  {"anglais": "cooking", "francais": "cuisine (action)"},
  {"anglais": "cool", "francais": "frais, cool, super"},
  {"anglais": "copy", "francais": "copier"},
  {"anglais": "corner", "francais": "coin"},
  {"anglais": "correct", "francais": "correct"},
  {"anglais": "cost", "francais": "coût, coûter"},
  {"anglais": "costume", "francais": "costume, déguisement"},
  {"anglais": "could", "francais": "pouvoir (conditionnel, passé)"},
  {"anglais": "country", "francais": "pays"},
  {"anglais": "countryside", "francais": "campagne"},
  {"anglais": "course", "francais": "cours, plat (repas)"},
  {"anglais": "cousin", "francais": "cousin(e)"},
  {"anglais": "cover", "francais": "couvrir, couverture"},
  {"anglais": "cow", "francais": "vache"},
  {"anglais": "crazy", "francais": "fou, folle"},
  {"anglais": "cream", "francais": "crème, beige"},
  {"anglais": "credit card", "francais": "carte de crédit"},
  {"anglais": "cricket", "francais": "cricket"},
  {"anglais": "cross", "francais": "croix, traverser"},
  {"anglais": "crossing", "francais": "passage piéton"},
  {"anglais": "crowd", "francais": "foule"},
  {"anglais": "crowded", "francais": "bondé"},
  {"anglais": "cry", "francais": "pleurer"},
  {"anglais": "cup", "francais": "tasse"},
  {"anglais": "cupboard", "francais": "placard"},
  {"anglais": "curry", "francais": "curry"},
  {"anglais": "curtain", "francais": "rideau"},
  {"anglais": "customer", "francais": "client"},
  {"anglais": "cut", "francais": "couper"},
  {"anglais": "cycle", "francais": "faire du vélo"},
  {"anglais": "cycling", "francais": "cyclisme"},
  {"anglais": "dad", "francais": "papa"},
  {"anglais": "daily", "francais": "quotidien"},
  {"anglais": "dance", "francais": "danse, danser"},
  {"anglais": "dancer", "francais": "danseur(euse)"},
  {"anglais": "dancing", "francais": "danse (action)"},
  {"anglais": "danger", "francais": "danger"},
  {"anglais": "dangerous", "francais": "dangereux"},
  {"anglais": "dark", "francais": "sombre, foncé"},
  {"anglais": "date", "francais": "date"},
  {"anglais": "daughter", "francais": "fille"},
  {"anglais": "day", "francais": "jour"},
  {"anglais": "dead", "francais": "mort"},
  {"anglais": "dear", "francais": "cher (lettre), chère"},
  {"anglais": "decide", "francais": "décider"},
  {"anglais": "deep", "francais": "profond"},
  {"anglais": "degree", "francais": "degré (température, angle)"},
  {"anglais": "delay", "francais": "retard, retarder"},
  {"anglais": "delicious", "francais": "délicieux"},
  {"anglais": "deliver", "francais": "livrer"},
  {"anglais": "dentist", "francais": "dentiste"},
  {"anglais": "department", "francais": "département, rayon"},
  {"anglais": "department store", "francais": "grand magasin"},
  {"anglais": "describe", "francais": "décrire"},
  {"anglais": "desert", "francais": "désert"},
  {"anglais": "design", "francais": "concevoir, design, dessin"},
  {"anglais": "desk", "francais": "bureau (meuble)"},
  {"anglais": "dessert", "francais": "dessert"},
  {"anglais": "details", "francais": "détails"},
  {"anglais": "diary", "francais": "agenda"},
  {"anglais": "dictionary", "francais": "dictionnaire"},
  {"anglais": "die", "francais": "mourir"},
  {"anglais": "difference", "francais": "différence"},
  {"anglais": "different", "francais": "différent"},
  {"anglais": "difficult", "francais": "difficile"},
  {"anglais": "digital", "francais": "numérique"},
  {"anglais": "dining room", "francais": "salle à manger"},
  {"anglais": "dinner", "francais": "dîner"},
  {"anglais": "dinosaur", "francais": "dinosaure"},
  {"anglais": "diploma", "francais": "diplôme"},
  {"anglais": "directions", "francais": "indications"},
  {"anglais": "dirty", "francais": "sale"},
  {"anglais": "disco", "francais": "discothèque"},
  {"anglais": "discount", "francais": "réduction"},
  {"anglais": "discover", "francais": "découvrir"},
  {"anglais": "discuss", "francais": "discuter"},
  {"anglais": "dish", "francais": "plat (repas, vaisselle)"},
  {"anglais": "dive", "francais": "plonger"},
  {"anglais": "diving", "francais": "plongée"},
  {"anglais": "do", "francais": "faire"},
  {"anglais": "doctor", "francais": "docteur, médecin"},
  {"anglais": "document", "francais": "document"},
  {"anglais": "dog", "francais": "chien"},
  {"anglais": "doll", "francais": "poupée"},
  {"anglais": "dollar", "francais": "dollar"},
  {"anglais": "dolphin", "francais": "dauphin"},
  {"anglais": "donkey", "francais": "âne"},
  {"anglais": "door", "francais": "porte"},
  {"anglais": "dot", "francais": "point"},
  {"anglais": "double", "francais": "double"},
  {"anglais": "down", "francais": "en bas"},
  {"anglais": "download", "francais": "télécharger, téléchargement"},
  {"anglais": "downstairs", "francais": "en bas (étage)"},
  {"anglais": "Dr", "francais": "Docteur (titre)"},
  {"anglais": "draw", "francais": "dessiner"},
  {"anglais": "drawer", "francais": "tiroir"},
  {"anglais": "drawing", "francais": "dessin"},
  {"anglais": "dream", "francais": "rêve, rêver"},
  {"anglais": "dress", "francais": "robe, s'habiller"},
  {"anglais": "dressed", "francais": "habillé"},
  {"anglais": "drink", "francais": "boisson, boire"},
  {"anglais": "drive", "francais": "conduire"},
  {"anglais": "driver", "francais": "conducteur"},
  {"anglais": "driving licence", "francais": "permis de conduire"},
  {"anglais": "drop", "francais": "laisser tomber"},
  {"anglais": "drugstore", "francais": "pharmacie"},
  {"anglais": "drum", "francais": "tambour"},
  {"anglais": "dry", "francais": "sec, sécher"},
  {"anglais": "duck", "francais": "canard"},
  {"anglais": "during", "francais": "pendant"},
  {"anglais": "DVD", "francais": "DVD"},
  {"anglais": "DVD player", "francais": "lecteur DVD"},
  {"anglais": "each", "francais": "chaque"},
  {"anglais": "each other", "francais": "l'un l'autre"},
  {"anglais": "ear", "francais": "oreille"},
  {"anglais": "early", "francais": "tôt"},
  {"anglais": "earn", "francais": "gagner (salaire)"},
  {"anglais": "earring", "francais": "boucle d'oreille"},
  {"anglais": "easily", "francais": "facilement"},
  {"anglais": "east", "francais": "est"},
  {"anglais": "easy", "francais": "facile"},
  {"anglais": "eat", "francais": "manger"},
  {"anglais": "egg", "francais": "œuf"},
  {"anglais": "electric", "francais": "électrique"},
  {"anglais": "electricity", "francais": "électricité"},
  {"anglais": "elephant", "francais": "éléphant"},
  {"anglais": "elevator", "francais": "ascenseur"},
  {"anglais": "else", "francais": "autre"},
  {"anglais": "email", "francais": "email, envoyer un email"},
  {"anglais": "empty", "francais": "vide"},
  {"anglais": "end", "francais": "fin, finir"},
  {"anglais": "engine", "francais": "moteur"},
  {"anglais": "engineer", "francais": "ingénieur"},
  {"anglais": "enjoy", "francais": "apprécier, aimer"},
  {"anglais": "enough", "francais": "assez"},
  {"anglais": "enter", "francais": "entrer, participer"},
  {"anglais": "entrance", "francais": "entrée"},
  {"anglais": "envelope", "francais": "enveloppe"},
  {"anglais": "environment", "francais": "environnement"},
  {"anglais": "equipment", "francais": "équipement"},
  {"anglais": "eraser", "francais": "gomme"},
  {"anglais": "especially", "francais": "particulièrement"},
  {"anglais": "euro", "francais": "euro"},
  {"anglais": "even", "francais": "même"},
  {"anglais": "evening", "francais": "soir"},
  {"anglais": "event", "francais": "événement"},
  {"anglais": "ever", "francais": "jamais"},
  {"anglais": "every", "francais": "chaque"},
  {"anglais": "everybody", "francais": "tout le monde"},
  {"anglais": "everyone", "francais": "tout le monde"},
  {"anglais": "everything", "francais": "tout"},
  {"anglais": "everywhere", "francais": "partout"},
  {"anglais": "exactly", "francais": "exactement"},
  {"anglais": "examination/exam", "francais": "examen"},
  {"anglais": "example", "francais": "exemple"},
  {"anglais": "excellent", "francais": "excellent"},
  {"anglais": "except", "francais": "sauf"},
  {"anglais": "excited", "francais": "excité"},
  {"anglais": "exciting", "francais": "excitant"},
  {"anglais": "excuse", "francais": "excuser"},
  {"anglais": "exercise", "francais": "exercice, faire de l'exercice"},
  {"anglais": "exhibition", "francais": "exposition"},
  {"anglais": "exit", "francais": "sortie"},
  {"anglais": "expensive", "francais": "cher (coûteux)"},
  {"anglais": "experience", "francais": "expérience"},
  {"anglais": "experiment", "francais": "expérience (scientifique)"},
  {"anglais": "explain", "francais": "expliquer"},
  {"anglais": "explore", "francais": "explorer"},
  {"anglais": "explorer", "francais": "explorateur"},
  {"anglais": "extra", "francais": "supplémentaire"},
  {"anglais": "eye", "francais": "œil"},
  {"anglais": "face", "francais": "visage"},
  {"anglais": "fact", "francais": "fait"},
  {"anglais": "factory", "francais": "usine"},
  {"anglais": "fail", "francais": "échouer"},
  {"anglais": "fair", "francais": "clair (cheveux), juste"},
  {"anglais": "fall", "francais": "automne, tomber"},
  {"anglais": "family", "francais": "famille"},
  {"anglais": "famous", "francais": "célèbre"},
  {"anglais": "fan", "francais": "ventilateur, fan"},
  {"anglais": "fantastic", "francais": "fantastique"},
  {"anglais": "far", "francais": "loin"},
  {"anglais": "farm", "francais": "ferme"},
  {"anglais": "farmer", "francais": "fermier"},
  {"anglais": "fashion", "francais": "mode"},
  {"anglais": "fast", "francais": "rapide, vite"},
  {"anglais": "fast food", "francais": "restauration rapide"},
  {"anglais": "fat", "francais": "gros"},
  {"anglais": "father", "francais": "père"},
  {"anglais": "favourite", "francais": "préféré"},
  {"anglais": "feel", "francais": "sentir, se sentir"},
  {"anglais": "feelings", "francais": "sentiments"},
  {"anglais": "festival", "francais": "festival"},
  {"anglais": "few", "francais": "peu (de)"},
  {"anglais": "field", "francais": "champ"},
  {"anglais": "file", "francais": "dossier, fichier"},
  {"anglais": "fill", "francais": "remplir"},
  {"anglais": "fill in", "francais": "remplir (formulaire)"},
  {"anglais": "film", "francais": "film"},
  {"anglais": "final", "francais": "final"},
  {"anglais": "finally", "francais": "finalement"},
  {"anglais": "find", "francais": "trouver"},
  {"anglais": "find out", "francais": "découvrir"},
  {"anglais": "fine", "francais": "bien, beau (temps)"},
  {"anglais": "finger", "francais": "doigt"},
  {"anglais": "finish", "francais": "finir"},
  {"anglais": "fire", "francais": "feu"},
  {"anglais": "first", "francais": "premier, d'abord"},
  {"anglais": "first name", "francais": "prénom"},
  {"anglais": "first of all", "francais": "tout d'abord"},
  {"anglais": "fish", "francais": "poisson, pêcher"},
  {"anglais": "fishing", "francais": "pêche"},
  {"anglais": "fit", "francais": "en forme, aller (taille)"},
  {"anglais": "fix", "francais": "réparer"},
  {"anglais": "flat", "francais": "appartement"},
  {"anglais": "flight", "francais": "vol (avion)"},
  {"anglais": "floor", "francais": "sol, étage"},
  {"anglais": "flower", "francais": "fleur"},
  {"anglais": "fly", "francais": "voler"},
  {"anglais": "fog", "francais": "brouillard"},
  {"anglais": "foggy", "francais": "brumeux"},
  {"anglais": "folder", "francais": "dossier"},
  {"anglais": "follow", "francais": "suivre"},
  {"anglais": "food", "francais": "nourriture"},
  {"anglais": "foot", "francais": "pied"},
  {"anglais": "football", "francais": "football"},
  {"anglais": "footballer", "francais": "footballeur"},
  {"anglais": "for", "francais": "pour"},
  {"anglais": "foreign", "francais": "étranger"},
  {"anglais": "forest", "francais": "forêt"},
  {"anglais": "forget", "francais": "oublier"},
  {"anglais": "fork", "francais": "fourchette"},
  {"anglais": "form", "francais": "formulaire"},
  {"anglais": "free", "francais": "libre, gratuit"},
  {"anglais": "French fries", "francais": "frites"},
  {"anglais": "fresh", "francais": "frais"},
  {"anglais": "fridge", "francais": "réfrigérateur"},
  {"anglais": "fried", "francais": "frit"},
  {"anglais": "friend", "francais": "ami(e)"},
  {"anglais": "friendly", "francais": "amical"},
  {"anglais": "frightened", "francais": "effrayé"},
  {"anglais": "from", "francais": "de"},
  {"anglais": "front", "francais": "avant, devant"},
  {"anglais": "fruit", "francais": "fruit"},
  {"anglais": "full", "francais": "plein"},
  {"anglais": "fun", "francais": "amusant, amusement"},
  {"anglais": "funny", "francais": "drôle"},
  {"anglais": "fur", "francais": "fourrure"},
  {"anglais": "furniture", "francais": "meubles"},
  {"anglais": "further", "francais": "plus loin, plus avancé"},
  {"anglais": "future", "francais": "futur"},
  {"anglais": "gallery", "francais": "galerie"},
  {"anglais": "game", "francais": "jeu"},
  {"anglais": "garage", "francais": "garage"},
  {"anglais": "garden", "francais": "jardin"},
  {"anglais": "garlic", "francais": "ail"},
  {"anglais": "gas", "francais": "essence, gaz"},
  {"anglais": "gas station", "francais": "station-service"},
  {"anglais": "gate", "francais": "portail"},
  {"anglais": "geography", "francais": "géographie"},
  {"anglais": "get", "francais": "obtenir, devenir, arriver"},
  {"anglais": "get back", "francais": "rentrer"},
  {"anglais": "get dressed", "francais": "s'habiller"},
  {"anglais": "get fit", "francais": "se mettre en forme"},
  {"anglais": "get married", "francais": "se marier"},
  {"anglais": "get off", "francais": "descendre (bus, train)"},
  {"anglais": "get on", "francais": "monter (bus, train)"},
  {"anglais": "get up", "francais": "se lever"},
  {"anglais": "gift", "francais": "cadeau"},
  {"anglais": "girl", "francais": "fille"},
  {"anglais": "girlfriend", "francais": "petite amie"},
  {"anglais": "give", "francais": "donner"},
  {"anglais": "give back", "francais": "rendre"},
  {"anglais": "glad", "francais": "content"},
  {"anglais": "glass", "francais": "verre"},
  {"anglais": "glasses", "francais": "lunettes"},
  {"anglais": "glove", "francais": "gant"},
  {"anglais": "go", "francais": "aller"},
  {"anglais": "goal", "francais": "but"},
  {"anglais": "gold", "francais": "or"},
  {"anglais": "golden", "francais": "doré"},
  {"anglais": "golf", "francais": "golf"},
  {"anglais": "good", "francais": "bon"},
  {"anglais": "good afternoon", "francais": "bonjour (après-midi)"},
  {"anglais": "goodbye", "francais": "au revoir"},
  {"anglais": "good evening", "francais": "bonsoir"},
  {"anglais": "good-looking", "francais": "beau, belle"},
  {"anglais": "good morning", "francais": "bonjour (matin)"},
  {"anglais": "good night", "francais": "bonne nuit"},
  {"anglais": "go out", "francais": "sortir"},
  {"anglais": "grade", "francais": "note, classe (niveau scolaire)"},
  {"anglais": "gram(me)", "francais": "gramme"},
  {"anglais": "grandchild", "francais": "petit-enfant"},
  {"anglais": "grand(d)ad", "francais": "papi"},
  {"anglais": "granddaughter", "francais": "petite-fille"},
  {"anglais": "grandfather", "francais": "grand-père"},
  {"anglais": "grandma", "francais": "mamie"},
  {"anglais": "grandmother", "francais": "grand-mère"},
  {"anglais": "grandpa", "francais": "papi"},
  {"anglais": "grandparent", "francais": "grand-parent"},
  {"anglais": "grandson", "francais": "petit-fils"},
  {"anglais": "granny", "francais": "mamie"},
  {"anglais": "grape", "francais": "raisin"},
  {"anglais": "grass", "francais": "herbe"},
  {"anglais": "great", "francais": "grand, super"},
  {"anglais": "green", "francais": "vert"},
  {"anglais": "grey", "francais": "gris"},
  {"anglais": "grilled", "francais": "grillé"},
  {"anglais": "grocery store", "francais": "épicerie"},
  {"anglais": "group", "francais": "groupe"},
  {"anglais": "grow", "francais": "grandir, pousser"},
  {"anglais": "grow up", "francais": "grandir (devenir adulte)"},
  {"anglais": "guess", "francais": "deviner"},
  {"anglais": "guest", "francais": "invité"},
  {"anglais": "guest-house", "francais": "maison d'hôtes"},
  {"anglais": "guide", "francais": "guide"},
  {"anglais": "guidebook", "francais": "guide (livre)"},
  {"anglais": "guitar", "francais": "guitare"},
  {"anglais": "guy", "francais": "gars, type"},
  {"anglais": "gym", "francais": "gymnase, salle de sport"},
  {"anglais": "hair", "francais": "cheveux"},
  {"anglais": "half", "francais": "moitié, demi"},
  {"anglais": "half-price", "francais": "moitié prix"},
  {"anglais": "hall", "francais": "hall, couloir"},
  {"anglais": "hand", "francais": "main"},
  {"anglais": "handbag", "francais": "sac à main"},
  {"anglais": "happen", "francais": "se passer, arriver"},
  {"anglais": "happy", "francais": "heureux"},
  {"anglais": "harbour", "francais": "port"},
  {"anglais": "hard", "francais": "dur, difficile"},
  {"anglais": "hat", "francais": "chapeau"},
  {"anglais": "hate", "francais": "détester"},
  {"anglais": "have", "francais": "avoir"},
  {"anglais": "have got to", "francais": "devoir"},
  {"anglais": "have to", "francais": "devoir"},
  {"anglais": "he", "francais": "il"},
  {"anglais": "head", "francais": "tête"},
  {"anglais": "headache", "francais": "mal de tête"},
  {"anglais": "headphones", "francais": "casque (audio)"},
  {"anglais": "headteacher", "francais": "directeur(trice) d'école"},
  {"anglais": "health", "francais": "santé"},
  {"anglais": "healthy", "francais": "sain, en bonne santé"},
  {"anglais": "hear", "francais": "entendre"},
  {"anglais": "heart", "francais": "cœur"},
  {"anglais": "heating", "francais": "chauffage"},
  {"anglais": "heavy", "francais": "lourd"},
  {"anglais": "helicopter", "francais": "hélicoptère"},
  {"anglais": "hello", "francais": "bonjour, salut"},
  {"anglais": "help", "francais": "aide, aider"},
  {"anglais": "helpful", "francais": "utile"},
  {"anglais": "her", "francais": "son/sa/ses (à elle), la/lui (pronom)"},
  {"anglais": "here", "francais": "ici"},
  {"anglais": "hers", "francais": "le/la sien(ne), les siens/siennes (à elle)"},
  {"anglais": "herself", "francais": "elle-même"},
  {"anglais": "hey", "francais": "hé, salut"},
  {"anglais": "hi", "francais": "salut"},
  {"anglais": "high", "francais": "haut, élevé"},
  {"anglais": "hill", "francais": "colline"},
  {"anglais": "him", "francais": "le/lui"},
  {"anglais": "himself", "francais": "lui-même"},
  {"anglais": "hip hop", "francais": "hip hop"},
  {"anglais": "his", "francais": "son/sa/ses (à lui), le/la sien(ne), les siens/siennes (à lui)"},
  {"anglais": "history", "francais": "histoire"},
  {"anglais": "hit", "francais": "frapper"},
  {"anglais": "hobby", "francais": "passe-temps"},
  {"anglais": "hockey", "francais": "hockey"},
  {"anglais": "hold", "francais": "tenir"},
  {"anglais": "holiday", "francais": "vacances"},
  {"anglais": "home", "francais": "maison, chez soi"},
  {"anglais": "homework", "francais": "devoirs"},
  {"anglais": "honey", "francais": "miel"},
  {"anglais": "hope", "francais": "espérer"},
  {"anglais": "horrible", "francais": "horrible"},
  {"anglais": "horror", "francais": "horreur"},
  {"anglais": "horse", "francais": "cheval"},
  {"anglais": "hospital", "francais": "hôpital"},
  {"anglais": "hot", "francais": "chaud"},
  {"anglais": "hotel", "francais": "hôtel"},
  {"anglais": "hour", "francais": "heure"},
  {"anglais": "house", "francais": "maison"},
  {"anglais": "housewife", "francais": "femme au foyer"},
  {"anglais": "how", "francais": "comment"},
  {"anglais": "however", "francais": "cependant"},
  {"anglais": "huge", "francais": "énorme"},
  {"anglais": "hungry", "francais": "avoir faim"},
  {"anglais": "hurry", "francais": "se dépêcher"},
  {"anglais": "hurt", "francais": "blesser, faire mal"},
  {"anglais": "husband", "francais": "mari"},
  {"anglais": "I", "francais": "je"},
  {"anglais": "ice", "francais": "glace"},
  {"anglais": "ice cream", "francais": "glace (crème glacée)"},
  {"anglais": "ice skating", "francais": "patinage sur glace"},
  {"anglais": "ID", "francais": "pièce d'identité"},
  {"anglais": "ID card", "francais": "carte d'identité"},
  {"anglais": "idea", "francais": "idée"},
  {"anglais": "identification", "francais": "identification"},
  {"anglais": "if", "francais": "si"},
  {"anglais": "ill", "francais": "malade"},
  {"anglais": "immediately", "francais": "immédiatement"},
  {"anglais": "important", "francais": "important"},
  {"anglais": "impossible", "francais": "impossible"},
  {"anglais": "improve", "francais": "améliorer"},
  {"anglais": "in", "francais": "dans, en"},
  {"anglais": "include", "francais": "inclure"},
  {"anglais": "including", "francais": "y compris"},
  {"anglais": "indoor", "francais": "intérieur"},
  {"anglais": "indoors", "francais": "à l'intérieur"},
  {"anglais": "information", "francais": "information(s)"},
  {"anglais": "in front of", "francais": "devant"},
  {"anglais": "ingredient", "francais": "ingrédient"},
  {"anglais": "insect", "francais": "insecte"},
  {"anglais": "inside", "francais": "à l'intérieur"},
  {"anglais": "instead", "francais": "au lieu"},
  {"anglais": "instead of", "francais": "au lieu de"},
  {"anglais": "instructions", "francais": "instructions"},
  {"anglais": "instrument", "francais": "instrument"},
  {"anglais": "interested", "francais": "intéressé"},
  {"anglais": "interesting", "francais": "intéressant"},
  {"anglais": "international", "francais": "international"},
  {"anglais": "internet", "francais": "internet"},
  {"anglais": "into", "francais": "dans (mouvement)"},
  {"anglais": "invent", "francais": "inventer"},
  {"anglais": "invention", "francais": "invention"},
  {"anglais": "invitation", "francais": "invitation"},
  {"anglais": "invite", "francais": "inviter"},
  {"anglais": "island", "francais": "île"},
  {"anglais": "it", "francais": "il/elle (neutre)"},
  {"anglais": "IT", "francais": "informatique"},
  {"anglais": "its", "francais": "son/sa/ses (neutre)"},
  {"anglais": "itself", "francais": "lui-même/elle-même (neutre)"},
  {"anglais": "jacket", "francais": "veste"},
  {"anglais": "jam", "francais": "confiture"},
  {"anglais": "jazz", "francais": "jazz"},
  {"anglais": "jeans", "francais": "jean"},
  {"anglais": "jewellery/jewelry", "francais": "bijoux"},
  {"anglais": "job", "francais": "travail, emploi"},
  {"anglais": "join", "francais": "rejoindre"},
  {"anglais": "journalist", "francais": "journaliste"},
  {"anglais": "journey", "francais": "voyage"},
  {"anglais": "juice", "francais": "jus"},
  {"anglais": "jump", "francais": "sauter"},
  {"anglais": "jumper", "francais": "pull"},
  {"anglais": "just", "francais": "juste, seulement"},
  {"anglais": "keep", "francais": "garder"},
  {"anglais": "key", "francais": "clé, touche (clavier)"},
  {"anglais": "keyboard", "francais": "clavier"},
  {"anglais": "kick", "francais": "coup de pied, donner un coup de pied"},
  {"anglais": "kid(s)", "francais": "enfant(s)"},
  {"anglais": "kilogramme (kg)", "francais": "kilogramme (kg)"},
  {"anglais": "kilometre (km)", "francais": "kilomètre (km)"},
  {"anglais": "kind", "francais": "gentil, sorte"},
  {"anglais": "king", "francais": "roi"},
  {"anglais": "kiss", "francais": "baiser, embrasser"},
  {"anglais": "kit", "francais": "kit, équipement"},
  {"anglais": "kitchen", "francais": "cuisine (pièce)"},
  {"anglais": "kite", "francais": "cerf-volant"},
  {"anglais": "knife", "francais": "couteau"},
  {"anglais": "know", "francais": "savoir, connaître"},
  {"anglais": "lake", "francais": "lac"},
  {"anglais": "lamp", "francais": "lampe"},
  {"anglais": "language", "francais": "langue, langage"},
  {"anglais": "laptop (computer)", "francais": "ordinateur portable"},
  {"anglais": "large", "francais": "grand, large"},
  {"anglais": "last", "francais": "dernier"},
  {"anglais": "late", "francais": "tard, en retard"},
  {"anglais": "later", "francais": "plus tard"},
  {"anglais": "latest", "francais": "le plus récent"},
  {"anglais": "laugh", "francais": "rire"},
  {"anglais": "lazy", "francais": "paresseux"},
  {"anglais": "learn", "francais": "apprendre"},
  {"anglais": "least", "francais": "le moins"},
  {"anglais": "leather", "francais": "cuir"},
  {"anglais": "leave", "francais": "partir, laisser"},
  {"anglais": "left", "francais": "gauche"},
  {"anglais": "leg", "francais": "jambe"},
  {"anglais": "lemon", "francais": "citron"},
  {"anglais": "lemonade", "francais": "limonade"},
  {"anglais": "lend", "francais": "prêter"},
  {"anglais": "length", "francais": "longueur"},
  {"anglais": "less", "francais": "moins"},
  {"anglais": "lesson", "francais": "leçon"},
  {"anglais": "let", "francais": "laisser, permettre"},
  {"anglais": "letter", "francais": "lettre"},
  {"anglais": "level", "francais": "niveau"},
  {"anglais": "library", "francais": "bibliothèque (lieu)"},
  {"anglais": "licence", "francais": "permis, licence"},
  {"anglais": "lie down", "francais": "s'allonger"},
  {"anglais": "life", "francais": "vie"},
  {"anglais": "lift", "francais": "ascenseur, prendre en voiture"},
  {"anglais": "light", "francais": "lumière, léger, clair"},
  {"anglais": "like", "francais": "comme, aimer"},
  {"anglais": "line", "francais": "ligne"},
  {"anglais": "lion", "francais": "lion"},
  {"anglais": "link", "francais": "lien"},
  {"anglais": "list", "francais": "liste"},
  {"anglais": "listen", "francais": "écouter"},
  {"anglais": "litre", "francais": "litre"},
  {"anglais": "little", "francais": "petit, peu"},
  {"anglais": "live", "francais": "vivre, habiter"},
  {"anglais": "living room", "francais": "salon"},
  {"anglais": "local", "francais": "local"},
  {"anglais": "long", "francais": "long"},
  {"anglais": "look", "francais": "regarder, avoir l'air"},
  {"anglais": "look after", "francais": "s'occuper de"},
  {"anglais": "look at", "francais": "regarder"},
  {"anglais": "look for", "francais": "chercher"},
  {"anglais": "look out", "francais": "faire attention"},
  {"anglais": "lorry", "francais": "camion"},
  {"anglais": "lose", "francais": "perdre"},
  {"anglais": "lost", "francais": "perdu"},
  {"anglais": "lots / a lot", "francais": "beaucoup"},
  {"anglais": "loud", "francais": "fort (son)"},
  {"anglais": "love", "francais": "amour, aimer"},
  {"anglais": "lovely", "francais": "charmant, adorable"},
  {"anglais": "low", "francais": "bas"},
  {"anglais": "luck", "francais": "chance"},
  {"anglais": "luckily", "francais": "heureusement"},
  {"anglais": "lucky", "francais": "chanceux"},
  {"anglais": "luggage", "francais": "bagages"},
  {"anglais": "lunch", "francais": "déjeuner"},
  {"anglais": "lunchtime", "francais": "heure du déjeuner"},
  {"anglais": "machine", "francais": "machine"},
  {"anglais": "mad", "francais": "fou"},
  {"anglais": "magazine", "francais": "magazine"},
  {"anglais": "mail", "francais": "courrier"},
  {"anglais": "main course", "francais": "plat principal"},
  {"anglais": "make", "francais": "faire, fabriquer"},
  {"anglais": "make sure (that)", "francais": "s'assurer (que)"},
  {"anglais": "make-up", "francais": "maquillage"},
  {"anglais": "man", "francais": "homme"},
  {"anglais": "manager", "francais": "directeur, manager"},
  {"anglais": "mango", "francais": "mangue"},
  {"anglais": "many", "francais": "beaucoup (de)"},
  {"anglais": "map", "francais": "carte (géographique)"},
  {"anglais": "mark", "francais": "marque, note"},
  {"anglais": "market", "francais": "marché"},
  {"anglais": "married", "francais": "marié"},
  {"anglais": "match", "francais": "match, allumette"},
  {"anglais": "maths/mathematics", "francais": "maths/mathématiques"},
  {"anglais": "matter", "francais": "affaire, importer"},
  {"anglais": "may", "francais": "pouvoir (permission, possibilité)"},
  {"anglais": "maybe", "francais": "peut-être"},
  {"anglais": "me", "francais": "moi, me"},
  {"anglais": "meal", "francais": "repas"},
  {"anglais": "mean", "francais": "signifier, vouloir dire"},
  {"anglais": "meat", "francais": "viande"},
  {"anglais": "mechanic", "francais": "mécanicien"},
  {"anglais": "medicine", "francais": "médicament"},
  {"anglais": "meet", "francais": "rencontrer"},
  {"anglais": "meeting", "francais": "réunion"},
  {"anglais": "melon", "francais": "melon"},
  {"anglais": "member", "francais": "membre"},
  {"anglais": "memory", "francais": "mémoire"},
  {"anglais": "menu", "francais": "menu"},
  {"anglais": "message", "francais": "message"},
  {"anglais": "metal", "francais": "métal"},
  {"anglais": "metre", "francais": "mètre"},
  {"anglais": "midday", "francais": "midi"},
  {"anglais": "middle", "francais": "milieu"},
  {"anglais": "midnight", "francais": "minuit"},
  {"anglais": "might", "francais": "pouvoir (possibilité faible)"},
  {"anglais": "mile", "francais": "mile"},
  {"anglais": "milk", "francais": "lait"},
  {"anglais": "million", "francais": "million"},
  {"anglais": "mind", "francais": "déranger, faire attention"},
  {"anglais": "mine", "francais": "le mien, la mienne, les miens, les miennes"},
  {"anglais": "mineral water", "francais": "eau minérale"},
  {"anglais": "minus", "francais": "moins"},
  {"anglais": "minute", "francais": "minute"},
  {"anglais": "mirror", "francais": "miroir"},
  {"anglais": "Miss", "francais": "Mademoiselle"},
  {"anglais": "miss", "francais": "manquer (qqn/qqch), rater"},
  {"anglais": "missing", "francais": "manquant"},
  {"anglais": "mistake", "francais": "erreur"},
  {"anglais": "mix", "francais": "mélanger"},
  {"anglais": "mobile (phone)", "francais": "téléphone portable"},
  {"anglais": "model", "francais": "modèle, maquette"},
  {"anglais": "modern", "francais": "moderne"},
  {"anglais": "mom", "francais": "maman"},
  {"anglais": "moment", "francais": "moment"},
  {"anglais": "money", "francais": "argent"},
  {"anglais": "monkey", "francais": "singe"},
  {"anglais": "month", "francais": "mois"},
  {"anglais": "monthly", "francais": "mensuel"},
  {"anglais": "moon", "francais": "lune"},
  {"anglais": "more", "francais": "plus"},
  {"anglais": "morning", "francais": "matin"},
  {"anglais": "most", "francais": "le plus"},
  {"anglais": "mother", "francais": "mère"},
  {"anglais": "motorbike", "francais": "moto"},
  {"anglais": "motorway", "francais": "autoroute"},
  {"anglais": "mountain", "francais": "montagne"},
  {"anglais": "mouse", "francais": "souris (animal, ordinateur)"},
  {"anglais": "mouth", "francais": "bouche"},
  {"anglais": "move", "francais": "bouger, déménager"},
  {"anglais": "movie", "francais": "film"},
  {"anglais": "movie star", "francais": "star de cinéma"},
  {"anglais": "movie theater", "francais": "cinéma"},
  {"anglais": "MP3 player", "francais": "lecteur MP3"},
  {"anglais": "Mr", "francais": "Monsieur"},
  {"anglais": "Mrs", "francais": "Madame (mariée)"},
  {"anglais": "Ms", "francais": "Madame (statut marital inconnu)"},
  {"anglais": "much", "francais": "beaucoup (de)"},
  {"anglais": "mug", "francais": "mug, tasse"},
  {"anglais": "mum", "francais": "maman"},
  {"anglais": "museum", "francais": "musée"},
  {"anglais": "mushroom", "francais": "champignon"},
  {"anglais": "music", "francais": "musique"},
  {"anglais": "musical", "francais": "musical"},
  {"anglais": "musician", "francais": "musicien"},
  {"anglais": "must", "francais": "devoir (obligation)"},
  {"anglais": "my", "francais": "mon, ma, mes"},
  {"anglais": "myself", "francais": "moi-même"},
  {"anglais": "name", "francais": "nom"},
  {"anglais": "national", "francais": "national"},
  {"anglais": "nationality", "francais": "nationalité"},
  {"anglais": "nature", "francais": "nature"},
  {"anglais": "natural", "francais": "naturel"},
  {"anglais": "near", "francais": "près de"},
  {"anglais": "nearly", "francais": "presque"},
  {"anglais": "neck", "francais": "cou"},
  {"anglais": "necklace", "francais": "collier"},
  {"anglais": "need", "francais": "avoir besoin de"},
  {"anglais": "neighbour", "francais": "voisin(e)"},
  {"anglais": "nervous", "francais": "nerveux"},
  {"anglais": "net", "francais": "filet, internet"},
  {"anglais": "never", "francais": "jamais"},
  {"anglais": "new", "francais": "nouveau"},
  {"anglais": "news", "francais": "nouvelles, informations"},
  {"anglais": "newspaper", "francais": "journal"},
  {"anglais": "next", "francais": "prochain, suivant"},
  {"anglais": "next to", "francais": "à côté de"},
  {"anglais": "nice", "francais": "gentil, agréable"},
  {"anglais": "night", "francais": "nuit"},
  {"anglais": "no", "francais": "non, aucun"},
  {"anglais": "nobody", "francais": "personne"},
  {"anglais": "noise", "francais": "bruit"},
  {"anglais": "noisy", "francais": "bruyant"},
  {"anglais": "noon", "francais": "midi"},
  {"anglais": "no one", "francais": "personne"},
  {"anglais": "normal", "francais": "normal"},
  {"anglais": "north", "francais": "nord"},
  {"anglais": "nose", "francais": "nez"},
  {"anglais": "not", "francais": "ne...pas"},
  {"anglais": "note", "francais": "note, remarquer"},
  {"anglais": "notebook", "francais": "cahier"},
  {"anglais": "nothing", "francais": "rien"},
  {"anglais": "notice", "francais": "remarquer, avis"},
  {"anglais": "now", "francais": "maintenant"},
  {"anglais": "number", "francais": "numéro, nombre"},
  {"anglais": "nurse", "francais": "infirmier(ère)"},
  {"anglais": "ocean", "francais": "océan"},
  {"anglais": "occupation", "francais": "profession"},
  {"anglais": "o'clock", "francais": "heure (pile)"},
  {"anglais": "of", "francais": "de"},
  {"anglais": "off", "francais": "éteint, hors de"},
  {"anglais": "offer", "francais": "offre, offrir"},
  {"anglais": "office", "francais": "bureau (lieu)"},
  {"anglais": "often", "francais": "souvent"},
  {"anglais": "oh", "francais": "oh"},
  {"anglais": "oil", "francais": "huile, pétrole"},
  {"anglais": "OK/okay", "francais": "OK, d'accord"},
  {"anglais": "old", "francais": "vieux, âgé"},
  {"anglais": "Olympic", "francais": "olympique"},
  {"anglais": "omelette", "francais": "omelette"},
  {"anglais": "on", "francais": "sur, allumé"},
  {"anglais": "once", "francais": "une fois"},
  {"anglais": "one", "francais": "un, on (pronom)"},
  {"anglais": "onion", "francais": "oignon"},
  {"anglais": "online", "francais": "en ligne"},
  {"anglais": "only", "francais": "seulement"},
  {"anglais": "open", "francais": "ouvert, ouvrir"},
  {"anglais": "opera", "francais": "opéra"},
  {"anglais": "opinion", "francais": "opinion"},
  {"anglais": "opposite", "francais": "en face de"},
  {"anglais": "or", "francais": "ou"},
  {"anglais": "orange", "francais": "orange"},
  {"anglais": "order", "francais": "commande, commander, ordre"},
  {"anglais": "other", "francais": "autre"},
  {"anglais": "our", "francais": "notre, nos"},
  {"anglais": "ours", "francais": "le/la nôtre, les nôtres"},
  {"anglais": "ourselves", "francais": "nous-mêmes"},
  {"anglais": "out", "francais": "dehors"},
  {"anglais": "outdoor", "francais": "extérieur"},
  {"anglais": "outdoors", "francais": "à l'extérieur"},
  {"anglais": "out of", "francais": "hors de"},
  {"anglais": "outside", "francais": "dehors, à l'extérieur"},
  {"anglais": "oven", "francais": "four"},
  {"anglais": "over", "francais": "au-dessus, plus de"},
  {"anglais": "own", "francais": "propre (possessif)"},
  {"anglais": "pack", "francais": "emballer, faire (valise)"},
  {"anglais": "page", "francais": "page"},
  {"anglais": "pain", "francais": "douleur"},
  {"anglais": "paint", "francais": "peinture, peindre"},
  {"anglais": "painter", "francais": "peintre"},
  {"anglais": "painting", "francais": "peinture (œuvre)"},
  {"anglais": "pale", "francais": "pâle"},
  {"anglais": "pair", "francais": "paire"},
  {"anglais": "paper", "francais": "papier"},
  {"anglais": "paragraph", "francais": "paragraphe"},
  {"anglais": "pardon", "francais": "pardon"},
  {"anglais": "parent", "francais": "parent"},
  {"anglais": "park", "francais": "parc, se garer"},
  {"anglais": "parking lot", "francais": "parking"},
  {"anglais": "parrot", "francais": "perroquet"},
  {"anglais": "part", "francais": "partie"},
  {"anglais": "partner", "francais": "partenaire"},
  {"anglais": "party", "francais": "fête"},
  {"anglais": "pass", "francais": "passer"},
  {"anglais": "passenger", "francais": "passager"},
  {"anglais": "passport", "francais": "passeport"},
  {"anglais": "password", "francais": "mot de passe"},
  {"anglais": "past", "francais": "passé"},
  {"anglais": "pasta", "francais": "pâtes"},
  {"anglais": "path", "francais": "chemin"},
  {"anglais": "pay", "francais": "payer"},
  {"anglais": "PC (personal computer)", "francais": "PC (ordinateur personnel)"},
  {"anglais": "pear", "francais": "poire"},
  {"anglais": "pen", "francais": "stylo"},
  {"anglais": "pence", "francais": "pence (pluriel de penny)"},
  {"anglais": "pencil", "francais": "crayon"},
  {"anglais": "pencil case", "francais": "trousse"},
  {"anglais": "penfriend", "francais": "correspondant"},
  {"anglais": "penny", "francais": "penny"},
  {"anglais": "people", "francais": "gens"},
  {"anglais": "pepper", "francais": "poivre"},
  {"anglais": "per", "francais": "par"},
  {"anglais": "perfect", "francais": "parfait"},
  {"anglais": "perform", "francais": "jouer (spectacle), interpréter"},
  {"anglais": "performance", "francais": "représentation, performance"},
  {"anglais": "perfume", "francais": "parfum"},
  {"anglais": "perhaps", "francais": "peut-être"},
  {"anglais": "person", "francais": "personne"},
  {"anglais": "pet", "francais": "animal de compagnie"},
  {"anglais": "petrol", "francais": "essence"},
  {"anglais": "petrol station", "francais": "station-service"},
  {"anglais": "pharmacy", "francais": "pharmacie"},
  {"anglais": "phone", "francais": "téléphone, téléphoner"},
  {"anglais": "photo(graph)", "francais": "photo(graphie)"},
  {"anglais": "photographer", "francais": "photographe"},
  {"anglais": "photography", "francais": "photographie"},
  {"anglais": "physics", "francais": "physique"},
  {"anglais": "piano", "francais": "piano"},
  {"anglais": "pick up", "francais": "ramasser, prendre (qqn)"},
  {"anglais": "picnic", "francais": "pique-nique"},
  {"anglais": "picture", "francais": "image, photo"},
  {"anglais": "piece", "francais": "morceau"},
  {"anglais": "pillow", "francais": "oreiller"},
  {"anglais": "pilot", "francais": "pilote"},
  {"anglais": "pink", "francais": "rose"},
  {"anglais": "pity", "francais": "pitié"},
  {"anglais": "pizza", "francais": "pizza"},
  {"anglais": "place", "francais": "endroit, lieu"},
  {"anglais": "plan", "francais": "plan, planifier"},
  {"anglais": "plane", "francais": "avion"},
  {"anglais": "plant", "francais": "plante"},
  {"anglais": "plastic", "francais": "plastique"},
  {"anglais": "plate", "francais": "assiette"},
  {"anglais": "platform", "francais": "quai"},
  {"anglais": "play", "francais": "jouer, pièce de théâtre"},
  {"anglais": "player", "francais": "joueur"},
  {"anglais": "playground", "francais": "cour de récréation"},
  {"anglais": "pleasant", "francais": "agréable"},
  {"anglais": "please", "francais": "s'il vous plaît"},
  {"anglais": "pleased", "francais": "content"},
  {"anglais": "plus", "francais": "plus"},
  {"anglais": "p.m.", "francais": "de l'après-midi/soir (post meridiem)"},
  {"anglais": "pocket", "francais": "poche"},
  {"anglais": "point", "francais": "pointer (du doigt)"},
  {"anglais": "police", "francais": "police"},
  {"anglais": "police car", "francais": "voiture de police"},
  {"anglais": "police officer", "francais": "policier"},
  {"anglais": "police station", "francais": "commissariat"},
  {"anglais": "polite", "francais": "poli"},
  {"anglais": "pool", "francais": "piscine"},
  {"anglais": "poor", "francais": "pauvre"},
  {"anglais": "pop", "francais": "pop (musique)"},
  {"anglais": "popular", "francais": "populaire"},
  {"anglais": "port", "francais": "port"},
  {"anglais": "possible", "francais": "possible"},
  {"anglais": "possibly", "francais": "peut-être, possiblement"},
  {"anglais": "post", "francais": "poster, courrier"},
  {"anglais": "postcard", "francais": "carte postale"},
  {"anglais": "poster", "francais": "affiche"},
  {"anglais": "post office", "francais": "bureau de poste"},
  {"anglais": "potato", "francais": "pomme de terre"},
  {"anglais": "pound (£)", "francais": "livre (£)"},
  {"anglais": "practice", "francais": "entraînement"},
  {"anglais": "practise", "francais": "s'entraîner"},
  {"anglais": "prefer / would prefer", "francais": "préférer"},
  {"anglais": "prepare", "francais": "préparer"},
  {"anglais": "present", "francais": "cadeau"},
  {"anglais": "pretty", "francais": "joli, assez"},
  {"anglais": "price", "francais": "prix"},
  {"anglais": "print", "francais": "imprimer"},
  {"anglais": "printer", "francais": "imprimante"},
  {"anglais": "prize", "francais": "prix (récompense)"},
  {"anglais": "probably", "francais": "probablement"},
  {"anglais": "problem", "francais": "problème"},
  {"anglais": "program", "francais": "programme (informatique)"},
  {"anglais": "programme", "francais": "programme (TV, etc.)"},
  {"anglais": "project", "francais": "projet"},
  {"anglais": "pull", "francais": "tirer"},
  {"anglais": "pupil", "francais": "élève"},
  {"anglais": "purple", "francais": "violet"},
  {"anglais": "purse", "francais": "porte-monnaie"},
  {"anglais": "push", "francais": "pousser"},
  {"anglais": "put", "francais": "mettre"},
  {"anglais": "put on", "francais": "mettre (vêtement)"},
  {"anglais": "puzzle", "francais": "puzzle, énigme"},
  {"anglais": "quarter", "francais": "quart"},
  {"anglais": "queen", "francais": "reine"},
  {"anglais": "question", "francais": "question"},
  {"anglais": "quick", "francais": "rapide"},
  {"anglais": "quickly", "francais": "rapidement"},
  {"anglais": "quiet", "francais": "calme, silencieux"},
  {"anglais": "quite", "francais": "assez"},
  {"anglais": "quiz", "francais": "quiz"},
  {"anglais": "rabbit", "francais": "lapin"},
  {"anglais": "race", "francais": "course, faire la course"},
  {"anglais": "racket", "francais": "raquette"},
  {"anglais": "radio", "francais": "radio"},
  {"anglais": "railway", "francais": "chemin de fer"},
  {"anglais": "rain", "francais": "pluie, pleuvoir"},
  {"anglais": "raincoat", "francais": "imperméable"},
  {"anglais": "rap", "francais": "rap"},
  {"anglais": "read", "francais": "lire"},
  {"anglais": "reading", "francais": "lecture"},
  {"anglais": "ready", "francais": "prêt"},
  {"anglais": "real", "francais": "vrai, réel"},
  {"anglais": "really", "francais": "vraiment"},
  {"anglais": "reason", "francais": "raison"},
  {"anglais": "receipt", "francais": "reçu"},
  {"anglais": "receive", "francais": "recevoir"},
  {"anglais": "receptionist", "francais": "réceptionniste"},
  {"anglais": "recipe", "francais": "recette"},
  {"anglais": "record", "francais": "enregistrer"},
  {"anglais": "red", "francais": "rouge"},
  {"anglais": "refrigerator", "francais": "réfrigérateur"},
  {"anglais": "relax", "francais": "se détendre"},
  {"anglais": "relaxing", "francais": "relaxant"},
  {"anglais": "remember", "francais": "se souvenir"},
  {"anglais": "rent", "francais": "louer"},
  {"anglais": "repair", "francais": "réparer"},
  {"anglais": "repeat", "francais": "répéter"},
  {"anglais": "rest", "francais": "repos, se reposer, reste"},
  {"anglais": "restaurant", "francais": "restaurant"},
  {"anglais": "return", "francais": "retour, revenir, rendre"},
  {"anglais": "review", "francais": "critique, réviser"},
  {"anglais": "rice", "francais": "riz"},
  {"anglais": "rich", "francais": "riche"},
  {"anglais": "ride", "francais": "balade, monter (vélo, cheval)"},
  {"anglais": "right", "francais": "droite, droit, correct"},
  {"anglais": "ring", "francais": "bague, sonner, appeler"},
  {"anglais": "river", "francais": "rivière"},
  {"anglais": "road", "francais": "route"},
  {"anglais": "roast", "francais": "rôtir, rôti"},
  {"anglais": "rock", "francais": "rocher, rock (musique)"},
  {"anglais": "roof", "francais": "toit"},
  {"anglais": "room", "francais": "pièce, chambre"},
  {"anglais": "round", "francais": "rond"},
  {"anglais": "roundabout", "francais": "rond-point"},
  {"anglais": "rubber", "francais": "gomme"},
  {"anglais": "rubbish", "francais": "déchets, ordures"},
  {"anglais": "rugby", "francais": "rugby"},
  {"anglais": "ruler", "francais": "règle (instrument)"},
  {"anglais": "run", "francais": "courir"},
  {"anglais": "runner", "francais": "coureur"},
  {"anglais": "running", "francais": "course à pied"},
  {"anglais": "sad", "francais": "triste"},
  {"anglais": "safe", "francais": "sûr, en sécurité"},
  {"anglais": "sail", "francais": "naviguer, faire de la voile"},
  {"anglais": "sailing", "francais": "voile (sport)"},
  {"anglais": "salad", "francais": "salade"},
  {"anglais": "sale", "francais": "vente, soldes"},
  {"anglais": "salt", "francais": "sel"},
  {"anglais": "same", "francais": "même"},
  {"anglais": "sandwich", "francais": "sandwich"},
  {"anglais": "sauce", "francais": "sauce"},
  {"anglais": "sausage", "francais": "saucisse"},
  {"anglais": "save", "francais": "économiser, sauver"},
  {"anglais": "say", "francais": "dire"},
  {"anglais": "scared", "francais": "effrayé"},
  {"anglais": "scarf", "francais": "écharpe"},
  {"anglais": "scary", "francais": "effrayant"},
  {"anglais": "school", "francais": "école"},
  {"anglais": "schoolchild", "francais": "écolier"},
  {"anglais": "science", "francais": "science"},
  {"anglais": "scientist", "francais": "scientifique"},
  {"anglais": "scissors", "francais": "ciseaux"},
  {"anglais": "scooter", "francais": "scooter, trottinette"},
  {"anglais": "screen", "francais": "écran"},
  {"anglais": "sea", "francais": "mer"},
  {"anglais": "season", "francais": "saison"},
  {"anglais": "seat", "francais": "siège, place"},
  {"anglais": "second", "francais": "deuxième, seconde"},
  {"anglais": "secretary", "francais": "secrétaire"},
  {"anglais": "see", "francais": "voir"},
  {"anglais": "seem", "francais": "sembler"},
  {"anglais": "selfie", "francais": "selfie"},
  {"anglais": "sell", "francais": "vendre"},
  {"anglais": "send", "francais": "envoyer"},
  {"anglais": "sentence", "francais": "phrase"},
  {"anglais": "serious", "francais": "sérieux"},
  {"anglais": "serve", "francais": "servir"},
  {"anglais": "set", "francais": "ensemble"},
  {"anglais": "several", "francais": "plusieurs"},
  {"anglais": "shall", "francais": "devoir (futur, suggestion)"},
  {"anglais": "shame", "francais": "honte, dommage"},
  {"anglais": "shampoo", "francais": "shampoing"},
  {"anglais": "share", "francais": "partager"},
  {"anglais": "she", "francais": "elle"},
  {"anglais": "sheep", "francais": "mouton"},
  {"anglais": "sheet", "francais": "feuille, drap"},
  {"anglais": "shelf", "francais": "étagère"},
  {"anglais": "ship", "francais": "navire"},
  {"anglais": "shirt", "francais": "chemise"},
  {"anglais": "shoe", "francais": "chaussure"},
  {"anglais": "shop", "francais": "magasin, faire les magasins"},
  {"anglais": "shop assistant", "francais": "vendeur"},
  {"anglais": "shopping", "francais": "shopping, achats"},
  {"anglais": "short", "francais": "court"},
  {"anglais": "shorts", "francais": "short"},
  {"anglais": "should", "francais": "devoir (conseil)"},
  {"anglais": "shout", "francais": "crier"},
  {"anglais": "show", "francais": "montrer, spectacle"},
  {"anglais": "shower", "francais": "douche"},
  {"anglais": "shut", "francais": "fermer"},
  {"anglais": "shy", "francais": "timide"},
  {"anglais": "sick", "francais": "malade"},
  {"anglais": "side", "francais": "côté"},
  {"anglais": "sightseeing", "francais": "tourisme"},
  {"anglais": "sign", "francais": "signe, panneau"},
  {"anglais": "silver", "francais": "argent (métal, couleur)"},
  {"anglais": "similar", "francais": "similaire"},
  {"anglais": "simple", "francais": "simple"},
  {"anglais": "since", "francais": "depuis"},
  {"anglais": "sing", "francais": "chanter"},
  {"anglais": "singer", "francais": "chanteur(euse)"},
  {"anglais": "singing", "francais": "chant"},
  {"anglais": "single", "francais": "célibataire, simple"},
  {"anglais": "sink", "francais": "évier"},
  {"anglais": "sister", "francais": "sœur"},
  {"anglais": "sit", "francais": "s'asseoir"},
  {"anglais": "sit down", "francais": "s'asseoir"},
  {"anglais": "site", "francais": "site"},
  {"anglais": "sitting room", "francais": "salon"},
  {"anglais": "size", "francais": "taille"},
  {"anglais": "skate", "francais": "patiner"},
  {"anglais": "skateboard", "francais": "skateboard"},
  {"anglais": "skateboarding", "francais": "skateboard (action)"},
  {"anglais": "skating", "francais": "patinage"},
  {"anglais": "ski", "francais": "skier, ski"},
  {"anglais": "skiing", "francais": "ski (action)"},
  {"anglais": "skirt", "francais": "jupe"},
  {"anglais": "sky", "francais": "ciel"},
  {"anglais": "sleep", "francais": "dormir"},
  {"anglais": "slice", "francais": "tranche"},
  {"anglais": "slim", "francais": "mince"},
  {"anglais": "slow", "francais": "lent"},
  {"anglais": "slowly", "francais": "lentement"},
  {"anglais": "small", "francais": "petit"},
  {"anglais": "smart", "francais": "élégant, intelligent"},
  {"anglais": "smoke", "francais": "fumer"},
  {"anglais": "smoking", "francais": "tabagisme"},
  {"anglais": "snack", "francais": "collation"},
  {"anglais": "snake", "francais": "serpent"},
  {"anglais": "snow", "francais": "neige, neiger"},
  {"anglais": "snowboard", "francais": "snowboard"},
  {"anglais": "snowboarding", "francais": "snowboard (action)"},
  {"anglais": "so", "francais": "donc, si"},
  {"anglais": "soap", "francais": "savon"},
  {"anglais": "soccer", "francais": "football (américain)"},
  {"anglais": "social media", "francais": "médias sociaux"},
  {"anglais": "sock", "francais": "chaussette"},
  {"anglais": "sofa", "francais": "canapé"},
  {"anglais": "soft", "francais": "doux"},
  {"anglais": "software", "francais": "logiciel"},
  {"anglais": "some", "francais": "quelques, du/de la/des"},
  {"anglais": "somebody", "francais": "quelqu'un"},
  {"anglais": "someone", "francais": "quelqu'un"},
  {"anglais": "something", "francais": "quelque chose"},
  {"anglais": "sometimes", "francais": "parfois"},
  {"anglais": "somewhere", "francais": "quelque part"},
  {"anglais": "son", "francais": "fils"},
  {"anglais": "song", "francais": "chanson"},
  {"anglais": "soon", "francais": "bientôt"},
  {"anglais": "sorry", "francais": "désolé"},
  {"anglais": "sort", "francais": "sorte"},
  {"anglais": "sound", "francais": "son, sembler"},
  {"anglais": "soup", "francais": "soupe"},
  {"anglais": "south", "francais": "sud"},
  {"anglais": "space", "francais": "espace"},
  {"anglais": "spare", "francais": "de rechange, libre"},
  {"anglais": "speak", "francais": "parler"},
  {"anglais": "speaker", "francais": "haut-parleur, orateur"},
  {"anglais": "special", "francais": "spécial"},
  {"anglais": "spell", "francais": "épeler"},
  {"anglais": "spelling", "francais": "orthographe"},
  {"anglais": "spend", "francais": "dépenser, passer (temps)"},
  {"anglais": "spoon", "francais": "cuillère"},
  {"anglais": "sport", "francais": "sport"},
  {"anglais": "sports centre", "francais": "centre sportif"},
  {"anglais": "spring", "francais": "printemps"},
  {"anglais": "square", "francais": "carré, place"},
  {"anglais": "stadium", "francais": "stade"},
  {"anglais": "staff", "francais": "personnel"},
  {"anglais": "stage", "francais": "scène"},
  {"anglais": "stairs", "francais": "escaliers"},
  {"anglais": "stamp", "francais": "timbre"},
  {"anglais": "stand", "francais": "être debout"},
  {"anglais": "star", "francais": "étoile, star"},
  {"anglais": "start", "francais": "commencer"},
  {"anglais": "station", "francais": "gare, station"},
  {"anglais": "stay", "francais": "rester"},
  {"anglais": "steak", "francais": "steak"},
  {"anglais": "steal", "francais": "voler, dérober"},
  {"anglais": "still", "francais": "encore, toujours"},
  {"anglais": "stomach", "francais": "estomac"},
  {"anglais": "stomach ache", "francais": "mal d'estomac"},
  {"anglais": "stop", "francais": "arrêter, arrêt"},
  {"anglais": "store", "francais": "magasin"},
  {"anglais": "storm", "francais": "orage, tempête"},
  {"anglais": "story", "francais": "histoire"},
  {"anglais": "straight", "francais": "droit, tout droit"},
  {"anglais": "strange", "francais": "étrange"},
  {"anglais": "strawberry", "francais": "fraise"},
  {"anglais": "street", "francais": "rue"},
  {"anglais": "striped", "francais": "rayé"},
  {"anglais": "stripes", "francais": "rayures"},
  {"anglais": "strong", "francais": "fort"},
  {"anglais": "student", "francais": "étudiant"},
  {"anglais": "studies", "francais": "études"},
  {"anglais": "study", "francais": "étudier"},
  {"anglais": "stuff", "francais": "trucs, affaires"},
  {"anglais": "subject", "francais": "sujet, matière (école)"},
  {"anglais": "success", "francais": "succès"},
  {"anglais": "successful", "francais": "réussi, qui a du succès"},
  {"anglais": "such", "francais": "tel, si"},
  {"anglais": "suddenly", "francais": "soudainement"},
  {"anglais": "sugar", "francais": "sucre"},
  {"anglais": "suggest", "francais": "suggérer"},
  {"anglais": "suit", "francais": "costume"},
  {"anglais": "suitcase", "francais": "valise"},
  {"anglais": "summer", "francais": "été"},
  {"anglais": "sun", "francais": "soleil"},
  {"anglais": "sunglasses", "francais": "lunettes de soleil"},
  {"anglais": "sunny", "francais": "ensoleillé"},
  {"anglais": "supermarket", "francais": "supermarché"},
  {"anglais": "supper", "francais": "souper"},
  {"anglais": "suppose", "francais": "supposer"},
  {"anglais": "sure", "francais": "sûr"},
  {"anglais": "surf", "francais": "surfer"},
  {"anglais": "surfboard", "francais": "planche de surf"},
  {"anglais": "surfing", "francais": "surf (action)"},
  {"anglais": "surname", "francais": "nom de famille"},
  {"anglais": "surprise", "francais": "surprise"},
  {"anglais": "surprised", "francais": "surpris"},
  {"anglais": "surprising", "francais": "surprenant"},
  {"anglais": "sweater", "francais": "pull"},
  {"anglais": "sweet", "francais": "sucré, bonbon"},
  {"anglais": "swim", "francais": "nager, baignade"},
  {"anglais": "swimming", "francais": "natation"},
  {"anglais": "swimming costume", "francais": "maillot de bain"},
  {"anglais": "swimming pool", "francais": "piscine"},
  {"anglais": "swimsuit", "francais": "maillot de bain"},
  {"anglais": "table", "francais": "table"},
  {"anglais": "table tennis", "francais": "tennis de table"},
  {"anglais": "tablet", "francais": "tablette"},
  {"anglais": "take", "francais": "prendre"},
  {"anglais": "take off", "francais": "enlever (vêtement), décoller (avion)"},
  {"anglais": "take part", "francais": "participer"},
  {"anglais": "talk", "francais": "parler, discussion"},
  {"anglais": "tall", "francais": "grand (taille)"},
  {"anglais": "tasty", "francais": "savoureux"},
  {"anglais": "taxi", "francais": "taxi"},
  {"anglais": "tea", "francais": "thé"},
  {"anglais": "teach", "francais": "enseigner"},
  {"anglais": "teacher", "francais": "enseignant"},
  {"anglais": "team", "francais": "équipe"},
  {"anglais": "technology", "francais": "technologie"},
  {"anglais": "teenager", "francais": "adolescent"},
  {"anglais": "telephone", "francais": "téléphone, téléphoner"},
  {"anglais": "television (TV)", "francais": "télévision (TV)"},
  {"anglais": "tell", "francais": "dire, raconter"},
  {"anglais": "temperature", "francais": "température"},
  {"anglais": "tennis", "francais": "tennis"},
  {"anglais": "tent", "francais": "tente"},
  {"anglais": "term", "francais": "trimestre"},
  {"anglais": "terrible", "francais": "terrible"},
  {"anglais": "test", "francais": "test"},
  {"anglais": "text", "francais": "texte, envoyer un message texte"},
  {"anglais": "textbook", "francais": "manuel scolaire"},
  {"anglais": "text message", "francais": "SMS, message texte"},
  {"anglais": "than", "francais": "que (comparaison)"},
  {"anglais": "thank", "francais": "remercier"},
  {"anglais": "thanks", "francais": "merci"},
  {"anglais": "thank you", "francais": "merci"},
  {"anglais": "that", "francais": "cela, ce/cette (là-bas), que"},
  {"anglais": "the", "francais": "le, la, les"},
  {"anglais": "theatre", "francais": "théâtre"},
  {"anglais": "their", "francais": "leur, leurs"},
  {"anglais": "theirs", "francais": "le/la leur, les leurs"},
  {"anglais": "them", "francais": "eux, les"},
  {"anglais": "themselves", "francais": "eux-mêmes"},
  {"anglais": "then", "francais": "ensuite"},
  {"anglais": "there", "francais": "là, il y a"},
  {"anglais": "these", "francais": "ces (ci)"},
  {"anglais": "they", "francais": "ils, elles"},
  {"anglais": "thin", "francais": "mince, fin"},
  {"anglais": "thing", "francais": "chose"},
  {"anglais": "think", "francais": "penser"},
  {"anglais": "thirsty", "francais": "avoir soif"},
  {"anglais": "this", "francais": "ceci, ce/cette (ci)"},
  {"anglais": "those", "francais": "ceux-là, ces (là-bas)"},
  {"anglais": "through", "francais": "à travers"},
  {"anglais": "throw", "francais": "jeter, lancer"},
  {"anglais": "thunderstorm", "francais": "orage"},
  {"anglais": "ticket", "francais": "billet"},
  {"anglais": "tidy", "francais": "rangé, ranger"},
  {"anglais": "tidy up", "francais": "ranger"},
  {"anglais": "tie", "francais": "cravate, attacher"},
  {"anglais": "tiger", "francais": "tigre"},
  {"anglais": "tights", "francais": "collants"},
  {"anglais": "till", "francais": "jusqu'à"},
  {"anglais": "time", "francais": "temps, heure, fois"},
  {"anglais": "timetable", "francais": "emploi du temps"},
  {"anglais": "tired", "francais": "fatigué"},
  {"anglais": "title", "francais": "titre"},
  {"anglais": "to", "francais": "à, pour"},
  {"anglais": "toast", "francais": "pain grillé"},
  {"anglais": "today", "francais": "aujourd'hui"},
  {"anglais": "toe", "francais": "orteil"},
  {"anglais": "together", "francais": "ensemble"},
  {"anglais": "toilet", "francais": "toilettes"},
  {"anglais": "tomato", "francais": "tomate"},
  {"anglais": "tomorrow", "francais": "demain"},
  {"anglais": "tonight", "francais": "ce soir"},
  {"anglais": "too", "francais": "aussi, trop"},
  {"anglais": "tooth", "francais": "dent"},
  {"anglais": "toothache", "francais": "mal de dents"},
  {"anglais": "toothbrush", "francais": "brosse à dents"},
  {"anglais": "top", "francais": "haut"},
  {"anglais": "topic", "francais": "sujet"},
  {"anglais": "total", "francais": "total"},
  {"anglais": "tour", "francais": "visite, tournée"},
  {"anglais": "tour guide", "francais": "guide touristique"},
  {"anglais": "tourist", "francais": "touriste"},
  {"anglais": "tourist information centre", "francais": "office de tourisme"},
  {"anglais": "towel", "francais": "serviette"},
  {"anglais": "town", "francais": "ville (petite)"},
  {"anglais": "toy", "francais": "jouet"},
  {"anglais": "traffic", "francais": "circulation"},
  {"anglais": "traffic light", "francais": "feu de circulation"},
  {"anglais": "train", "francais": "train, s'entraîner"},
  {"anglais": "training", "francais": "entraînement"},
  {"anglais": "trainer", "francais": "entraîneur, basket (chaussure)"},
  {"anglais": "tram", "francais": "tramway"},
  {"anglais": "transport", "francais": "transport"},
  {"anglais": "travel", "francais": "voyager"},
  {"anglais": "tree", "francais": "arbre"},
  {"anglais": "trip", "francais": "voyage, excursion"},
  {"anglais": "trouble", "francais": "problème, ennui"},
  {"anglais": "trousers", "francais": "pantalon"},
  {"anglais": "true", "francais": "vrai"},
  {"anglais": "try", "francais": "essayer"},
  {"anglais": "try on", "francais": "essayer (vêtement)"},
  {"anglais": "T-shirt", "francais": "T-shirt"},
  {"anglais": "tune", "francais": "mélodie, air"},
  {"anglais": "turn", "francais": "tourner"},
  {"anglais": "turn off", "francais": "éteindre"},
  {"anglais": "turn on", "francais": "allumer"},
  {"anglais": "twice", "francais": "deux fois"},
  {"anglais": "type", "francais": "type, taper (clavier)"},
  {"anglais": "tyre", "francais": "pneu"},
  {"anglais": "umbrella", "francais": "parapluie"},
  {"anglais": "uncle", "francais": "oncle"},
  {"anglais": "under", "francais": "sous"},
  {"anglais": "underground", "francais": "métro, souterrain"},
  {"anglais": "understand", "francais": "comprendre"},
  {"anglais": "unfortunately", "francais": "malheureusement"},
  {"anglais": "unhappy", "francais": "malheureux"},
  {"anglais": "uniform", "francais": "uniforme"},
  {"anglais": "university", "francais": "université"},
  {"anglais": "until", "francais": "jusqu'à"},
  {"anglais": "unusual", "francais": "inhabituel"},
  {"anglais": "up", "francais": "en haut"},
  {"anglais": "upload", "francais": "téléverser"},
  {"anglais": "upset", "francais": "contrarié"},
  {"anglais": "upstairs", "francais": "en haut (étage)"},
  {"anglais": "us", "francais": "nous"},
  {"anglais": "use", "francais": "utiliser"},
  {"anglais": "useful", "francais": "utile"},
  {"anglais": "usual", "francais": "habituel"},
  {"anglais": "usually", "francais": "habituellement"},
  {"anglais": "v/versus", "francais": "contre"},
  {"anglais": "variety", "francais": "variété"},
  {"anglais": "various", "francais": "divers"},
  {"anglais": "vegetable", "francais": "légume"},
  {"anglais": "very", "francais": "très"},
  {"anglais": "video", "francais": "vidéo"},
  {"anglais": "video game", "francais": "jeu vidéo"},
  {"anglais": "view", "francais": "vue"},
  {"anglais": "village", "francais": "village"},
  {"anglais": "violin", "francais": "violon"},
  {"anglais": "visit", "francais": "visiter, visite"},
  {"anglais": "visitor", "francais": "visiteur"},
  {"anglais": "vocabulary", "francais": "vocabulaire"},
  {"anglais": "volleyball", "francais": "volleyball"},
  {"anglais": "wait", "francais": "attendre"},
  {"anglais": "waiter", "francais": "serveur"},
  {"anglais": "waitress", "francais": "serveuse"},
  {"anglais": "wake", "francais": "réveiller"},
  {"anglais": "wake up", "francais": "se réveiller"},
  {"anglais": "walk", "francais": "marcher, promenade"},
  {"anglais": "walking", "francais": "marche"},
  {"anglais": "wall", "francais": "mur"},
  {"anglais": "wallet", "francais": "portefeuille"},
  {"anglais": "want", "francais": "vouloir"},
  {"anglais": "wardrobe", "francais": "armoire"},
  {"anglais": "warm", "francais": "chaud, chaleureux"},
  {"anglais": "wash", "francais": "laver"},
  {"anglais": "washing machine", "francais": "machine à laver"},
  {"anglais": "washing-up", "francais": "vaisselle"},
  {"anglais": "wash up", "francais": "faire la vaisselle"},
  {"anglais": "watch", "francais": "regarder, montre"},
  {"anglais": "water", "francais": "eau"},
  {"anglais": "way", "francais": "chemin, manière"},
  {"anglais": "we", "francais": "nous"},
  {"anglais": "wear", "francais": "porter (vêtement)"},
  {"anglais": "weather", "francais": "temps (météo)"},
  {"anglais": "web", "francais": "web, toile"},
  {"anglais": "web page", "francais": "page web"},
  {"anglais": "website", "francais": "site web"},
  {"anglais": "week", "francais": "semaine"},
  {"anglais": "weekday", "francais": "jour de la semaine"},
  {"anglais": "weekend", "francais": "week-end"},
  {"anglais": "weekly", "francais": "hebdomadaire"},
  {"anglais": "welcome", "francais": "bienvenue"},
  {"anglais": "well", "francais": "bien"},
  {"anglais": "well known", "francais": "bien connu"},
  {"anglais": "west", "francais": "ouest"},
  {"anglais": "wet", "francais": "mouillé"},
  {"anglais": "whale", "francais": "baleine"},
  {"anglais": "what", "francais": "quoi, que, quel"},
  {"anglais": "wheel", "francais": "roue"},
  {"anglais": "when", "francais": "quand"},
  {"anglais": "where", "francais": "où"},
  {"anglais": "which", "francais": "lequel, laquelle, lesquels, lesquelles, qui, que"},
  {"anglais": "while", "francais": "pendant que"},
  {"anglais": "white", "francais": "blanc"},
  {"anglais": "who", "francais": "qui"},
  {"anglais": "whole", "francais": "entier"},
  {"anglais": "whose", "francais": "dont, à qui"},
  {"anglais": "why", "francais": "pourquoi"},
  {"anglais": "wide", "francais": "large"},
  {"anglais": "wife", "francais": "femme, épouse"},
  {"anglais": "wifi", "francais": "wifi"},
  {"anglais": "wild", "francais": "sauvage"},
  {"anglais": "wildlife", "francais": "faune sauvage"},
  {"anglais": "will ('ll)", "francais": "auxiliaire du futur"},
  {"anglais": "win", "francais": "gagner"},
  {"anglais": "wind", "francais": "vent"},
  {"anglais": "window", "francais": "fenêtre"},
  {"anglais": "windsurfing", "francais": "planche à voile"},
  {"anglais": "windy", "francais": "venteux"},
  {"anglais": "winner", "francais": "gagnant"},
  {"anglais": "winter", "francais": "hiver"},
  {"anglais": "wish", "francais": "souhait, souhaiter"},
  {"anglais": "with", "francais": "avec"},
  {"anglais": "without", "francais": "sans"},
  {"anglais": "woman", "francais": "femme"},
  {"anglais": "wonderful", "francais": "merveilleux"},
  {"anglais": "wood", "francais": "bois"},
  {"anglais": "wooden", "francais": "en bois"},
  {"anglais": "wool", "francais": "laine"},
  {"anglais": "word", "francais": "mot"},
  {"anglais": "work", "francais": "travail, travailler"},
  {"anglais": "worker", "francais": "travailleur"},
  {"anglais": "work out", "francais": "faire de l'exercice"},
  {"anglais": "world", "francais": "monde"},
  {"anglais": "worried", "francais": "inquiet"},
  {"anglais": "worry", "francais": "s'inquiéter"},
  {"anglais": "worse", "francais": "pire"},
  {"anglais": "worst", "francais": "le pire"},
  {"anglais": "would", "francais": "auxiliaire du conditionnel"},
  {"anglais": "wow", "francais": "ouah"},
  {"anglais": "write", "francais": "écrire"},
  {"anglais": "write down", "francais": "noter"},
  {"anglais": "writer", "francais": "écrivain"},
  {"anglais": "writing", "francais": "écriture"},
  {"anglais": "wrong", "francais": "faux, mauvais"},
  {"anglais": "yeah", "francais": "ouais"},
  {"anglais": "year", "francais": "année"},
  {"anglais": "yellow", "francais": "jaune"},
  {"anglais": "yes", "francais": "oui"},
  {"anglais": "yesterday", "francais": "hier"},
  {"anglais": "yet", "francais": "encore, déjà"},
  {"anglais": "yog(h)urt", "francais": "yaourt"},
  {"anglais": "you", "francais": "tu, vous"},
  {"anglais": "young", "francais": "jeune"},
  {"anglais": "your", "francais": "ton, ta, tes, votre, vos"},
  {"anglais": "yours", "francais": "le/la tien(ne), les tiens/tiennes, le/la vôtre, les vôtres"},
  {"anglais": "yourself", "francais": "toi-même, vous-même"},
  {"anglais": "zero", "francais": "zéro"},
  {"anglais": "zoo", "francais": "zoo"}
];
